version: '3.9'

services:
  server:
    image: nginx:alpine
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m
      timeout: 2s
      retries: 3
    logging:
      options:
        max-size: "100m"
        max-file: "10"
    ports:
      - 80:80
    volumes:
      - ./data:/epg
      - ./nginx.conf:/etc/nginx/conf.d/default.conf